import { CurrenciesAnimations } from '@/assets/currencies/CurrenciesAnimations';

export default {
  data() { return { CurrenciesAnimations }; },
  ActI: [
    {
      currencyId: 'coinSilver',
      images: CurrenciesAnimations.coin.silver,
      initialPositionX: 600,
      value: 1,
    },
    {
      currencyId: 'coinSilver',
      images: CurrenciesAnimations.coin.silver,
      initialPositionX: 700,
      value: 1,
    },
    {
      currencyId: 'coinGold',
      images: CurrenciesAnimations.coin.gold,
      initialPositionX: 800,
      value: 1,
    },
    {
      currencyId: 'coinGold',
      images: CurrenciesAnimations.coin.gold,
      initialPositionX: 1000,
      value: 1,
    },
    {
      currencyId: 'coinRed',
      images: CurrenciesAnimations.coin.red,
      initialPositionX: 1100,
      value: 1,
    },
    {
      currencyId: 'coinRed',
      images: CurrenciesAnimations.coin.red,
      initialPositionX: 1200,
      value: 1,
    },
    {
      currencyId: 'gemYellow',
      images: CurrenciesAnimations.gem.yellow,
      initialPositionX: 1400,
      value: 1,
    },
    {
      currencyId: 'gemYellow',
      images: CurrenciesAnimations.gem.yellow,
      initialPositionX: 1500,
      value: 1,
    },
    {
      currencyId: 'gemGreen',
      images: CurrenciesAnimations.gem.green,
      initialPositionX: 1600,
      value: 1,
    },
    {
      currencyId: 'gemGreen',
      images: CurrenciesAnimations.gem.green,
      initialPositionX: 1700,
      value: 1,
    },
    {
      currencyId: 'gemBlue',
      images: CurrenciesAnimations.gem.blue,
      initialPositionX: 1800,
      value: 1,
    },
    {
      currencyId: 'gemBlue',
      images: CurrenciesAnimations.gem.blue,
      initialPositionX: 1900,
      value: 1,
    },
    {
      currencyId: 'gemRed',
      images: CurrenciesAnimations.gem.red,
      initialPositionX: 2100,
      value: 1,
    },
    {
      currencyId: 'gemRed',
      images: CurrenciesAnimations.gem.red,
      initialPositionX: 2200,
      value: 1,
    },
    {
      currencyId: 'gemGrey',
      images: CurrenciesAnimations.gem.grey,
      initialPositionX: 2300,
      value: 1,
    },
    {
      currencyId: 'gemGrey',
      images: CurrenciesAnimations.gem.grey,
      initialPositionX: 2400,
      value: 1,
    },
  ],
  ActII: [
    {
      currencyId: 'coinSilver',
      images: CurrenciesAnimations.coin.silver,
      initialPositionX: 600,
      value: 1,
    },
    {
      currencyId: 'coinSilver',
      images: CurrenciesAnimations.coin.silver,
      initialPositionX: 700,
      value: 1,
    },
    {
      currencyId: 'coinGold',
      images: CurrenciesAnimations.coin.gold,
      initialPositionX: 800,
      value: 1,
    },
    {
      currencyId: 'coinGold',
      images: CurrenciesAnimations.coin.gold,
      initialPositionX: 1000,
      value: 1,
    },
    {
      currencyId: 'coinRed',
      images: CurrenciesAnimations.coin.red,
      initialPositionX: 1100,
      value: 1,
    },
    {
      currencyId: 'coinRed',
      images: CurrenciesAnimations.coin.red,
      initialPositionX: 1200,
      value: 1,
    },
    {
      currencyId: 'gemYellow',
      images: CurrenciesAnimations.gem.yellow,
      initialPositionX: 1400,
      value: 1,
    },
    {
      currencyId: 'gemYellow',
      images: CurrenciesAnimations.gem.yellow,
      initialPositionX: 1500,
      value: 1,
    },
    {
      currencyId: 'gemGreen',
      images: CurrenciesAnimations.gem.green,
      initialPositionX: 1600,
      value: 1,
    },
    {
      currencyId: 'gemGreen',
      images: CurrenciesAnimations.gem.green,
      initialPositionX: 1700,
      value: 1,
    },
    {
      currencyId: 'gemBlue',
      images: CurrenciesAnimations.gem.blue,
      initialPositionX: 1800,
      value: 1,
    },
    {
      currencyId: 'gemBlue',
      images: CurrenciesAnimations.gem.blue,
      initialPositionX: 1900,
      value: 1,
    },
    {
      currencyId: 'gemRed',
      images: CurrenciesAnimations.gem.red,
      initialPositionX: 2100,
      value: 1,
    },
    {
      currencyId: 'gemRed',
      images: CurrenciesAnimations.gem.red,
      initialPositionX: 2200,
      value: 1,
    },
    {
      currencyId: 'gemGrey',
      images: CurrenciesAnimations.gem.grey,
      initialPositionX: 2300,
      value: 1,
    },
    {
      currencyId: 'gemGrey',
      images: CurrenciesAnimations.gem.grey,
      initialPositionX: 2400,
      value: 1,
    },
  ],
  // Дополнительные акты и их враги...
};
